services:
  - type: web
    name: resume-screener
    env: python
    plan: starter
    repo: <REPLACE_WITH_YOUR_REPO_URL>
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT
    envVars:
      - key: RESUME_ENABLE_EMBEDDINGS
        value: '0'
      - key: DATABASE_URL
        fromDatabase:
          name: resume-screener-db

databases:
  - name: resume-screener-db
    engine: POSTGRES
    plan: starter
